name: build-and-deploy

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:unit

      - name: Generate coverage report
        run: npm run coverage

      - name: Upload coverage to Gitea
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Build Vite app
        run: npm run build

      # https://github.com/appleboy/scp-action
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: dist/*
          strip_components: 1
          target: /var/www/lan
